
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 14 17:39:09 EDT 2011
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int ELSE = 11;
  public static final int PLUS = 3;
  public static final int DEFINE = 18;
  public static final int RPAREN = 8;
  public static final int THEN = 10;
  public static final int SEMI = 2;
  public static final int WHILE = 13;
  public static final int RETURN = 21;
  public static final int END = 20;
  public static final int FI = 12;
  public static final int IF = 9;
  public static final int LPAREN = 7;
  public static final int ID = 24;
  public static final int OD = 15;
  public static final int DO = 14;
  public static final int COMMA = 23;
  public static final int NUMBER = 22;
  public static final int EOF = 0;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int PROC = 19;
  public static final int UNTIL = 17;
  public static final int ASSIGN = 6;
  public static final int REPEAT = 16;
}

